<a href="https://colab.research.google.com/github/Kishan-Kumar-Zalavadia/MachineLearning/blob/main/Practice_MLWeek1Day1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.23.5'

In [5]:
arr_1d = np.array([1,2,3])
arr_1d

array([1, 2, 3])

In [11]:
print("Shape:",arr_1d.shape)
print(f"Shape: {arr_1d.shape}")

Shape: (3,)
Shape: (3,)


In [13]:
arr_1d[2]

3

In [34]:
rand_array = np.random.randint(1,4,[2,4])
rand_array

array([[1, 2, 2, 2],
       [3, 2, 3, 1]])

In [48]:
print(rand_array.sum())
print(rand_array.min())
print(rand_array.max())
print(np.mean(rand_array))
print(np.std(rand_array))

16
1
3
2.0
0.7071067811865476


In [51]:
import pandas as pd
pd.__version__

'1.5.3'

In [52]:
df = pd.read_csv("https://raw.githubusercontent.com/omairaasim/machine_learning/master/project_11_k_nearest_neighbor/iphone_purchase_records.csv")

In [54]:
df.head()

Gender  Age  Salary  Purchase Iphone
0    Male   19   19000                0
1    Male   35   20000                0
2  Female   26   43000                0
3  Female   27   57000                0
4    Male   19   76000                0

In [55]:
df.tail()

Gender  Age  Salary  Purchase Iphone
395  Female   46   41000                1
396    Male   51   23000                1
397  Female   50   20000                1
398    Male   36   33000                0
399  Female   49   36000                1

In [58]:
df.head(2)

Gender  Age  Salary  Purchase Iphone
0   Male   19   19000                0
1   Male   35   20000                0

In [57]:
df.tail(2)

Gender  Age  Salary  Purchase Iphone
398    Male   36   33000                0
399  Female   49   36000                1

In [86]:
df[["Gender","Age","Salary"]].head(2)

Gender  Age  Salary
0   Male   19   19000
1   Male   35   20000

In [75]:
df.loc[3]

Gender             Female
Age                    27
Salary              57000
Purchase Iphone         0
Name: 3, dtype: object

In [77]:
#loc[row, column]
df.loc[3,"Gender"]

'Female'

In [83]:
df.loc[2:4,["Gender","Age"]]

Gender  Age
2  Female   26
3  Female   27
4    Male   19

In [106]:
df.loc[4:7,"Gender":"Salary"]

Gender  Age  Salary
4    Male   19   76000
5    Male   27   58000
6  Female   27   84000
7  Female   32  150000

In [113]:
df.iloc[4:7,[0,1]]

Gender  Age
4    Male   19
5    Male   27
6  Female   27

In [114]:
df.iloc[:,[0,1]]

Gender  Age
0      Male   19
1      Male   35
2    Female   26
3    Female   27
4      Male   19
..      ...  ...
395  Female   46
396    Male   51
397  Female   50
398    Male   36
399  Female   49

[400 rows x 2 columns]

In [115]:
df.iloc[[2,5],:]

Gender  Age  Salary  Purchase Iphone
2  Female   26   43000                0
5    Male   27   58000                0

In [107]:
df.iloc[4:7,0:2]

Gender  Age
4    Male   19
5    Male   27
6  Female   27

In [103]:
df.loc[0:4]

Gender  Age  Salary  Purchase Iphone
0    Male   19   19000                0
1    Male   35   20000                0
2  Female   26   43000                0
3  Female   27   57000                0
4    Male   19   76000                0

In [104]:
#last index is not considered in iloc
df.iloc[0:4]

Gender  Age  Salary  Purchase Iphone
0    Male   19   19000                0
1    Male   35   20000                0
2  Female   26   43000                0
3  Female   27   57000                0

In [121]:
# Dictionaries are case-sensitive
df.loc[df["Age"] == 30]

Gender  Age  Salary  Purchase Iphone
37     Male   30   49000                0
43     Male   30   15000                0
48     Male   30  135000                1
80     Male   30   80000                0
84   Female   30   62000                0
91   Female   30  116000                0
128    Male   30   17000                0
132    Male   30   87000                0
137    Male   30  107000                1
143    Male   30   89000                0
196  Female   30   79000                0

In [122]:
df.keys()

Index(['Gender', 'Age', 'Salary', 'Purchase Iphone'], dtype='object')

In [125]:
df.values

array([['Male', 19, 19000, 0],
       ['Male', 35, 20000, 0],
       ['Female', 26, 43000, 0],
       ...,
       ['Female', 50, 20000, 1],
       ['Male', 36, 33000, 0],
       ['Female', 49, 36000, 1]], dtype=object)

#Practice 1 - Numpy
##1) Create a 4X3 NumPy array called array
##2) Create a 3x4 random array called rand_array
##3) Check shape (side by side) for both rand_array, and array
##4) Apply matrix product

In [129]:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10,11,12]])
rand_array = np.random.rand(3,4) # Hint: If the original array has dimensions 4x3, make sure the rand_array has dimensions of 3x4.
print(rand_array.shape, array.shape)
print(np.matmul(array, rand_array))

(3, 4) (4, 3)
[[ 4.12851329  4.34146338  5.38615827  2.42238946]
 [10.54990688 10.29618519 13.53762841  5.91636015]
 [16.97130047 16.25090699 21.68909856  9.41033083]
 [23.39269406 22.2056288  29.8405687  12.90430152]]


#Practice - Pandas
##1) Rename "salary" to "income".
##2) Calculate the counts of females and males.
##3) Create separate datasets for females and males.
##4) Determine the minimum and maximum ages.
##5) Examine salary and iPhone purchase status.

In [134]:
df.rename(columns={"Salary":"Income"}, inplace=True)
print(df["Gender"].value_counts())
print ("-"*5)
female = df.loc[df["Gender"] == "Female"]
male = df.loc[df["Gender"] == "Male"]

min_age_female = np.min(female["Age"])
max_age_female = np.max(female["Age"])
min_age_male = np.min(male["Age"])
max_age_male = np.max(male["Age"])

print ("Young Female")
print (female.loc[female["Age"]==min_age_female])
print ("-"*5)
print ("Old Female")
print (female.loc[female["Age"]==max_age_female])
print ("-"*5)
print ("Young Male")
print (male.loc[male["Age"]==min_age_male])
print ("-"*5)
print ("Old Male")
print (male.loc[male["Age"]==max_age_male])

Female    204
Male      196
Name: Gender, dtype: int64
-----
Young Female
     Gender  Age  Income  Purchase Iphone
51   Female   18   44000                0
141  Female   18   68000                0
165  Female   18   86000                0
-----
Old Female
     Gender  Age  Income  Purchase Iphone
215  Female   60  108000                1
370  Female   60   46000                1
-----
Young Male
   Gender  Age  Income  Purchase Iphone
14   Male   18   82000                0
76   Male   18   52000                0
-----
Old Male
    Gender  Age  Income  Purchase Iphone
223   Male   60  102000                1
272   Male   60   42000                1
355   Male   60   34000                1
371   Male   60   83000                1
393   Male   60   42000                1


#DRY (DO NOT REPEAT YOURSELF)

In [137]:
def age_gender_analysis(inp:str) -> None:
    """
    Analyze age and gender to identify potential buyers.

    Parameter
    ---------
    inp:
      The gender for which age analysis will be performed.

    """
    data = df.loc[df["Gender"] == inp]
    min_age = np.min(data["Age"])
    max_age = np.max(data["Age"])
    print (f"Young {inp}")
    print (data.loc[data["Age"]== min_age])
    print ("-"*5)
    print (f"Old {inp}")
    print (data.loc[data["Age"]== max_age])

df.rename(columns={"Salary":"Income"}, inplace=True)
stat = df["Gender"].value_counts()
print (stat)
print ("-"*5)
for inp in ["Female", "Male"]:
    age_gender_analysis(inp)

Female    204
Male      196
Name: Gender, dtype: int64
-----
Young Female
     Gender  Age  Income  Purchase Iphone
51   Female   18   44000                0
141  Female   18   68000                0
165  Female   18   86000                0
-----
Old Female
     Gender  Age  Income  Purchase Iphone
215  Female   60  108000                1
370  Female   60   46000                1
Young Male
   Gender  Age  Income  Purchase Iphone
14   Male   18   82000                0
76   Male   18   52000                0
-----
Old Male
    Gender  Age  Income  Purchase Iphone
223   Male   60  102000                1
272   Male   60   42000                1
355   Male   60   34000                1
371   Male   60   83000                1
393   Male   60   42000                1
